import { RecoveryCase } from "./types";

export const sampleCases: RecoveryCase[] = [
  {
    id: "RC_001",
    paymentId: "pay_demo_001",
    amount: 2499,
    currency: "INR",
    paymentMethod: "CARD",
    failureReason: "NETWORK_ERROR",
    attemptCount: 1,
    lastAttemptHoursAgo: 2,
    successfulPayments: 12,
    failedPayments: 1,
    previousActions: [],
    customerMessage: "Payment failed while checking out.",
    status: "AT_RISK",
  },

  {
    id: "RC_002",
    paymentId: "pay_demo_002",
    amount: 4999,
    currency: "INR",
    paymentMethod: "CARD",
    failureReason: "INSUFFICIENT_FUNDS",
    attemptCount: 3,
    lastAttemptHoursAgo: 30,
    successfulPayments: 8,
    failedPayments: 3,
    previousActions: [
      "RETRY_NOW",
      "RETRY_LATER",
      "RETRY_NOW",
    ],
    customerMessage: "Please try again later.",
    status: "AT_RISK",
  },

  {
    id: "RC_003",
    paymentId: "pay_demo_003",
    amount: 7999,
    currency: "INR",
    paymentMethod: "CARD",
    failureReason: "CARD_EXPIRED",
    attemptCount: 1,
    lastAttemptHoursAgo: 12,
    successfulPayments: 16,
    failedPayments: 1,
    previousActions: [],
    customerMessage: "My old card may have expired.",
    status: "AT_RISK",
  },

  {
    id: "RC_004",
    paymentId: "inv_demo_004",
    amount: 24500,
    currency: "INR",
    paymentMethod: "BANK_TRANSFER",
    failureReason: "INVOICE_OVERDUE",
    attemptCount: 1,
    lastAttemptHoursAgo: 72,
    successfulPayments: 21,
    failedPayments: 2,
    previousActions: ["SEND_PAYMENT_LINK"],
    customerMessage:
      "Accounts team expects to clear the invoice next week.",
    status: "AT_RISK",
  },

  {
    id: "RC_005",
    paymentId: "pay_demo_005",
    amount: 1299,
    currency: "INR",
    paymentMethod: "UPI",
    failureReason: "ISSUER_UNAVAILABLE",
    attemptCount: 1,
    lastAttemptHoursAgo: 1,
    successfulPayments: 6,
    failedPayments: 1,
    previousActions: [],
    customerMessage: "UPI payment failed unexpectedly.",
    status: "AT_RISK",
  },

  {
    id: "RC_006",
    paymentId: "pay_demo_006",
    amount: 14999,
    currency: "INR",
    paymentMethod: "CARD",
    failureReason: "PAYMENT_METHOD_INVALID",
    attemptCount: 2,
    lastAttemptHoursAgo: 24,
    successfulPayments: 4,
    failedPayments: 2,
    previousActions: ["RETRY_NOW"],
    customerMessage: "Please tell me how I can complete the payment.",
    status: "AT_RISK",
  },
];